### ISSUE TITLE
Unable to start Neo4j server. Already reviewed plugin versions.

### ISSUE THREAD

**Issue by mrkarezina** [graphaware/neo4j-nlp#110]
I am unable to start the server after adding the plugins in the plugins folder and changing the config file. The neo4j version is: 3.4.0 (Enterprise Edition)

I am using the Desktop app, which shows me the database is "Killed" almost immediately, is the STARTING stage, before it ever get to RUNNING. 

Plugin versions:
![screen shot 2018-08-02 at 4 34 14 pm](https://user-images.githubusercontent.com/39007518/43609442-074acd02-9672-11e8-854d-cd10a931355c.png)

**Change to config file**

>  dbms.directories.import=import
dbms.security.auth_enabled=false
dbms.memory.heap.initial_size=2512m
dbms.memory.heap.max_size=4512m  
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.enabled=true
com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
dbms.security.procedures.whitelist=ga.nlp.*

**Stack trace:**

> 2018-08-02 20:20:55.889+0000 INFO  Neo4j Server shutdown initiated by request
Active database: graph.db
Directories in use:
  home:         /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0
  config:       /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/conf
  logs:         /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/logs
  plugins:      /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/plugins
  import:       /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/import
  data:         /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/data
  certificates: /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/certificates
  run:          /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/run
Starting Neo4j.
2018-08-02 20:21:26.466+0000 INFO  ======== Neo4j 3.4.0 ========
2018-08-02 20:21:26.543+0000 INFO  Starting...
2018-08-02 20:21:28.285+0000 INFO  Initiating metrics...
2018-08-02 20:21:29.387+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-08-02 20:21:29.429+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NLP, using com.graphaware.nlp.module.NLPBootstrapper
2018-08-02 20:21:29.591+0000 INFO  Registering module NLP with GraphAware Runtime.
2018-08-02 20:21:29.595+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2018-08-02 20:21:29.614+0000 INFO  Sending metrics to CSV file at /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/metrics
2018-08-02 20:21:30.104+0000 INFO  Bolt enabled on 127.0.0.1:11006.
2018-08-02 20:21:30.275+0000 INFO  Shutting down GraphAware Runtime... 
2018-08-02 20:21:30.276+0000 INFO  Shutting down module NLP
2018-08-02 20:21:30.276+0000 INFO  Terminating task scheduler...
2018-08-02 20:21:30.277+0000 INFO  Task scheduler terminated successfully.
2018-08-02 20:21:30.277+0000 INFO  GraphAware Runtime shut down.
2018-08-02 20:21:30.284+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Could not start GraphAware Runtime because the database didn't get to a usable state within 5 minutes.
2018-08-02 20:21:30.286+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7487b142' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7487b142' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7487b142' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7487b142' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/smith/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-0d0202d7-e740-43e3-8049-76a31e8e0f7a/installation-3.4.0/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:39)
	at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:78)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@66c38e51' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 9 more
Caused by: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:137)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:114)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:87)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:78)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:323)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2018-08-02 20:21:30.288+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by mrkarezina** [comment]
After reviewing the issues I got things running by using the snapshot version of the  nlp-stanfordnlp that I dowloaded as specified in issue 86:

Neo4j fails to start with GraphAware NLP plugin, because of java version error

**Comment by SUBHAMILA** [comment]
which version of java do i need to avoid this error ?
can you help me with it?
