### ISSUE TITLE
Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.RuntimeException: Unsupported language : n/a

### ISSUE THREAD

**Issue by saptwa** [graphaware/neo4j-nlp#111]
I'm using the following plugins:

**graphaware-nlp-3.4.0.52.8.jar
graphaware-server-community-all-3.4.0.52.jar
nlp-stanfordnlp-3.4.0.52.11.jar**

When trying to call the 'ga.nlp.annotate' procedure using:

```
MATCH (n:News)
CALL ga.nlp.annotate({text: n.text, id: id(n)})
YIELD result
MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result)
RETURN result
```

I get the following error:

```
  File "/Users/rishi/models/unsupervised/graphaware_nlp/graphaware.py", line 131, in annotate
    session.run("MATCH (n:Text) CALL ga.nlp.annotate({text: n.text, id: id(n), pipeline: 'customStopWords'}) YIELD result MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result) RETURN result")
  File "/Users/rishi/.virtualenvs/keyphrase-extraction-centrality/lib/python3.6/site-packages/neo4j/v1/api.py", line 331, in run
    self._connection.fetch()
  File "/Users/rishi/.virtualenvs/keyphrase-extraction-centrality/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 290, in fetch
    return self._fetch()
  File "/Users/rishi/.virtualenvs/keyphrase-extraction-centrality/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 330, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/rishi/.virtualenvs/keyphrase-extraction-centrality/lib/python3.6/site-packages/neo4j/v1/result.py", line 70, in on_failure
    raise CypherError.hydrate(**metadata)
neo4j.exceptions.ClientError: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.RuntimeException: Unsupported language : n/a
```
Here is the stack trace:

```
2018-08-08 03:43:26.739+0000 INFO  Notifying listeners for event {}
2018-08-08 03:43:26.798+0000 ERROR Unsupported language : n/a
java.lang.RuntimeException: Unsupported language : n/a
	at com.graphaware.nlp.NLPManager.checkTextLanguage(NLPManager.java:236)
	at com.graphaware.nlp.NLPManager.annotateTextAndPersist(NLPManager.java:136)
	at com.graphaware.nlp.NLPManager.annotateTextAndPersist(NLPManager.java:131)
	at com.graphaware.nlp.dsl.procedure.AnnotateProcedure.annotate(AnnotateProcedure.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:648)
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.callProcedure(ProcedureRegistry.java:219)
	at org.neo4j.kernel.impl.proc.Procedures.callProcedure(Procedures.java:290)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:1072)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder.procedureCallWrite(AllStoreHolder.java:852)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$6.apply(TransactionBoundQueryContext.scala:812)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$6.apply(TransactionBoundQueryContext.scala:812)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callProcedure(TransactionBoundQueryContext.scala:875)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callReadWriteProcedure(TransactionBoundQueryContext.scala:813)
	at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:149)
	at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:149)
	at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
	at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:41)
	at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateIterator(ExceptionTranslationSupport.scala:47)
	at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.translateIterator(ExceptionTranslatingQueryContext.scala:41)
	at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.callReadWriteProcedure(ExceptionTranslatingQueryContext.scala:149)
	at org.neo4j.cypher.internal.runtime.interpreted.DelegatingQueryContext.callReadWriteProcedure(DelegatingQueryContext.scala:216)
	at org.neo4j.cypher.internal.runtime.EagerReadWriteCallMode.callProcedure(ProcedureCallMode.scala:64)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.org$neo4j$cypher$internal$runtime$interpreted$pipes$ProcedureCallPipe$$call(ProcedureCallPipe.scala:83)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe$$anon$$$$e6882d5096c8b8441ac36d3c0cc459e$$$$ateResultsByAppending$1.apply(ProcedureCallPipe.scala:67)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe$$anon$$$$e6882d5096c8b8441ac36d3c0cc459e$$$$ateResultsByAppending$1.apply(ProcedureCallPipe.scala:65)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator.hasNext(ResultIterator.scala:60)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator.foreach(ResultIterator.scala:48)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator.to(ResultIterator.scala:48)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:294)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator.toList(ResultIterator.scala:48)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.EagerResultIterator.<init>(ResultIterator.scala:34)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.ClosingIterator.toEager(ResultIterator.scala:52)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.InterpretedExecutionResultBuilderFactory$InterpretedExecutionWorkflowBuilder.buildResultIterator(DefaultExecutionResultBuilderFactory.scala:158)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.BaseExecutionResultBuilderFactory$BaseExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:106)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.BaseExecutionResultBuilderFactory$BaseExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:77)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:97)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:80)
	at org.neo4j.cypher.internal.compatibility.v3_4.runtime.BuildInterpretedExecutionPlan$InterpretedExecutionPlan.run(BuildInterpretedExecutionPlan.scala:111)
	at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(LatestRuntimeVariablePlannerCompatibility.scala:128)
	at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(LatestRuntimeVariablePlannerCompatibility.scala:124)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper.run(LatestRuntimeVariablePlannerCompatibility.scala:124)
	at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:119)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:61)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI$1.start(TransactionStateMachineSPI.java:144)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:444)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:259)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:240)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:81)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:457)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:225)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```
I'm attaching the logs herein for reference.
[debug.log](https://github.com/graphaware/neo4j-nlp/files/2268858/debug.log)
[neo4j.log](https://github.com/graphaware/neo4j-nlp/files/2268859/neo4j.log)

I'm able to create the pipeline without any errors.
Could some please help me out?

**Comment by saptwa** [comment]
I'm able to create a pipeline without any errors

**Comment by ikwattro** [comment]
@saptwa It means the text you are trying to annotate is too small for a language to be detected.

Do this : 

```
CALL ga.nlp.config.set('SETTING_fallbackLanguage', 'en')
```

And disable the language check when you annotate : 

```
CALL ga.nlp.annotate({text: n.text, id: id(n), checkLanguage: false})
```

**Comment by saptwa** [comment]
Thanks for the prompt reply!

As it turns out the first document in my corpus contained only one word 'Facebook'. I guess that's why it wasn't able to detect the language.

**Comment by sgm0107** [comment]
![image](https://user-images.githubusercontent.com/10553503/51288386-dc271c80-19b0-11e9-941c-aba8b6edc012.png)

Using 3.5.1 Neo4J and using all 3.5.1 Jars for plugins 
I am getting the NullPointerException when I call ga.nlp.annotate. I followed the instructions above 

Please help

**Comment by merq-rodriguez** [comment]
I have the same problem and I have not been able to solve it...
