### ISSUE TITLE
Failed to start neo4j db after followed guide on installing graphaware nlp

### ISSUE THREAD

**Issue by AltheimIcarus** [graphaware/neo4j-nlp#113]
I followed exactly the guide on README to install graphaware nlp on my neo4j db v3.4.0
using:

- graphaware-nlp-3.4.0.52.8.jar
- graphaware-server-enterprise-all-3.4.0.52.jar
- nlp-stanfordnlp-3.4.0.52.8.jar

Later on, my db failed to start. Attached below is the log.

2018-08-08 09:56:24.013+0000 INFO  Neo4j Server shutdown initiated by request
2018-08-08 09:56:36.455+0000 INFO  ======== Neo4j 3.4.0 ========
2018-08-08 09:56:36.486+0000 INFO  Starting...
2018-08-08 09:56:37.745+0000 INFO  Initiating metrics...
2018-08-08 09:56:38.462+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-08-08 09:56:38.483+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NLP, using com.graphaware.nlp.module.NLPBootstrapper
2018-08-08 09:56:38.563+0000 INFO  Registering module NLP with GraphAware Runtime.
2018-08-08 09:56:38.565+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2018-08-08 09:56:38.567+0000 INFO  Sending metrics to CSV file at C:\Users\user\.Neo4jDesktop\neo4jDatabases\database-ef36e36e-fb3d-4225-981b-d5ea627eb5a7\installation-3.4.0\metrics
2018-08-08 09:56:39.190+0000 INFO  Bolt enabled on 127.0.0.1:7687.
**2018-08-08 09:56:41.619+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2018-08-08 09:56:41.621+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2018-08-08 09:56:44.582+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2018-08-08 09:56:44.583+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2018-08-08 09:56:47.580+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2018-08-08 09:56:47.581+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2018-08-08 09:56:50.581+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2018-08-08 09:56:50.581+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2018-08-08 09:56:53.581+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2018-08-08 09:56:53.582+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2018-08-08 09:56:56.579+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2018-08-08 09:56:56.580+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)**
2018-08-08 09:56:57.655+0000 INFO  Shutting down GraphAware Runtime... 
2018-08-08 09:56:57.655+0000 INFO  Shutting down module NLP
2018-08-08 09:56:57.656+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Could not start GraphAware Runtime because the database didn't get to a usable state within 5 minutes.
2018-08-08 09:56:57.656+0000 INFO  Terminating task scheduler...
2018-08-08 09:56:57.656+0000 INFO  Task scheduler terminated successfully.
2018-08-08 09:56:57.657+0000 INFO  GraphAware Runtime shut down.
2018-08-08 09:56:57.663+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@642c6148' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@642c6148' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@642c6148' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@642c6148' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Users\user\.Neo4jDesktop\neo4jDatabases\database-ef36e36e-fb3d-4225-981b-d5ea627eb5a7\installation-3.4.0\data\databases\graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:39)
	at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:78)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@862a676' was successfully initialized, but failed to start. Please see the attached cause exception "module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 9 more
Caused by: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:137)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:114)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:87)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:78)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:323)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2018-08-08 09:56:57.664+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by AltheimIcarus** [comment]
**FIXED**
The plugin download page sorted the plugins wrongly. Some older version is displayed on top of latest version.
