### ISSUE TITLE
Cannot start db after installing APOC plugin

### ISSUE THREAD

**Issue by fnfbraga** [graphaware/neo4j-nlp#137]
If I remove the APOC plugin the db starts normally with no errors
here's the error message after adding APOC:

2018-12-11 17:44:06.156+0000 INFO  ======== Neo4j 3.4.10 ========
2018-12-11 17:44:06.197+0000 INFO  Starting...
2018-12-11 17:44:07.626+0000 INFO  Initiating metrics...
2018-12-11 17:44:08.325+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-12-11 17:44:08.357+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NLP, using com.graphaware.nlp.module.NLPBootstrapper
2018-12-11 17:44:08.454+0000 INFO  Registering module NLP with GraphAware Runtime.
2018-12-11 17:44:08.460+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2018-12-11 17:44:08.480+0000 INFO  Sending metrics to CSV file at /home/fnb/.config/Neo4j Desktop/Application/neo4jDatabases/database-70e8c28d-f5bd-4790-9d54-dc8632073074/installation-3.4.10/metrics
2018-12-11 17:44:08.827+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-12-11 17:44:11.499+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2018-12-11 17:44:11.499+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2018-12-11 17:44:35.740+0000 INFO  Shutting down GraphAware Runtime... 
2018-12-11 17:44:35.740+0000 INFO  Shutting down module NLP
2018-12-11 17:44:35.741+0000 INFO  Terminating task scheduler...
2018-12-11 17:44:35.741+0000 INFO  Task scheduler terminated successfully.
2018-12-11 17:44:35.741+0000 INFO  GraphAware Runtime shut down.
2018-12-11 17:44:35.744+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Could not start GraphAware Runtime because the database didn't get to a usable state within 5 minutes.
2018-12-11 17:44:35.751+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2c3d8f83' was successfully initialized, but failed to start. Please see the attached cause exception "class org.jsoup.nodes.LeafNode overrides final method childNodeSize.()I". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2c3d8f83' was successfully initialized, but failed to start. Please see the attached cause exception "class org.jsoup.nodes.LeafNode overrides final method childNodeSize.()I".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2c3d8f83' was successfully initialized, but failed to start. Please see the attached cause exception "class org.jsoup.nodes.LeafNode overrides final method childNodeSize.()I".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2c3d8f83' was successfully initialized, but failed to start. Please see the attached cause exception "class org.jsoup.nodes.LeafNode overrides final method childNodeSize.()I".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /home/fnb/.config/Neo4j Desktop/Application/neo4jDatabases/database-70e8c28d-f5bd-4790-9d54-dc8632073074/installation-3.4.10/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:39)
	at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:78)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@2d14f347' was successfully initialized, but failed to start. Please see the attached cause exception "class org.jsoup.nodes.LeafNode overrides final method childNodeSize.()I".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 9 more
Caused by: java.lang.VerifyError: class org.jsoup.nodes.LeafNode overrides final method childNodeSize.()I
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:161)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:138)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:111)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:85)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:323)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more

**Comment by fnfbraga** [comment]
I re-installed and it is working now
