### ISSUE TITLE
[Enricher] ConceptNet5 stops server

### ISSUE THREAD

**Issue by rubinho101** [graphaware/neo4j-nlp#139]
Hello,

when performing the enricher
`MATCH (n:Tag)
CALL ga.nlp.enrich.concept({enricher: 'conceptnet5', tag: n, depth:1, admittedRelationships:["IsA","PartOf"]})
YIELD result
RETURN result`

it forces the server to stop with the following error:
`ERROR Error while improting hierarchy for omar_mateen (en). Ignored! com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.graphaware.nlp.enrich.conceptnet5.ConceptNet5EdgeResult, and Java type class com.graphaware.nlp.enrich.conceptnet5.ConceptNet5EdgeResult, and MIME media type text/html; charset=utf-8 was not found
com.google.common.util.concurrent.UncheckedExecutionException: com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.graphaware.nlp.enrich.conceptnet5.ConceptNet5EdgeResult, and Java type class com.graphaware.nlp.enrich.conceptnet5.ConceptNet5EdgeResult, and MIME media type text/html; charset=utf-8 was not found
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at com.graphaware.nlp.enrich.conceptnet5.ConceptNet5Client.queryByStart(ConceptNet5Client.java:77)
	at com.graphaware.nlp.enrich.conceptnet5.ConceptNet5Importer.lambda$importHierarchy$2(ConceptNet5Importer.java:78)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.graphaware.nlp.enrich.conceptnet5.ConceptNet5Importer.importHierarchy(ConceptNet5Importer.java:76)
	at com.graphaware.nlp.enrich.conceptnet5.ConceptNet5Enricher.lambda$importConcept$1(ConceptNet5Enricher.java:99)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
...`

any ideas?

**Comment by alenegro81** [comment]
The problem occurs since there is a limit to how many calls you can do to Concept Net 5, 6000 per hour. We solved the issue by creating a local instance of concept net 5, modifying the limit on the python script and pointing the plugin to the local instance (exists a parameter for it).

**Comment by ikwattro** [comment]
@alenegro81 Maybe it would be nice to catch the exception and throw something more meaningful.

**Comment by alenegro81** [comment]
good idea.
