### ISSUE TITLE
Neo.ClientError.Procedure.ProcedureNotFound

### ISSUE THREAD

**Issue by Anqi525** [graphaware/neo4j-nlp#148]
I am trying to use Neo4j to do a nlp project
Trying to install GraphAware based on your [documentation](https://github.com/graphaware/neo4j-nlp).
I downloaded all the jar files into the plugin, and append the lines into config file.
![1](https://user-images.githubusercontent.com/52260600/60269200-fe0bc000-98bb-11e9-8169-363edd4bcc32.PNG)
![2](https://user-images.githubusercontent.com/52260600/60269201-fe0bc000-98bb-11e9-9868-b867495af921.PNG)
I also edited the setting under the graph in neo4j. 
![3](https://user-images.githubusercontent.com/52260600/60269290-2abfd780-98bc-11e9-9e58-f86919f75159.PNG)

However, below is the image when I try to call ga,nlp
![4](https://user-images.githubusercontent.com/52260600/60269378-56db5880-98bc-11e9-94b1-703fc9c83ef4.PNG)

Could you helping me with this issue? Trying to spend lots of time to figure out this.

Best regards,
Angie

**Comment by ikwattro** [comment]
Hi @Anqi525 ,

You forgot to add the neo4j-nlp plugin . Also please use stanford and not opennlp as we don't really have upgraded opennlp to the latest versions

https://products.graphaware.com/

**Comment by Anqi525** [comment]
I added the neo4j-nlp plugin, but I cannot even start my database now.
The following is the error message from the logs:


2019-06-27 14:50:09.047+0000 INFO  Neo4j Server shutdown initiated by request
2019-06-27 14:50:16.636+0000 INFO  ======== Neo4j 3.5.6 ========
2019-06-27 14:50:16.644+0000 INFO  Starting...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/anwu/.Neo4jDesktop/neo4jDatabases/database-5bf995b6-ab88-41d1-a418-e49e1819fdba/installation-3.5.6/plugins/nlp-opennlp-3.3.2.52.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/anwu/.Neo4jDesktop/neo4jDatabases/database-5bf995b6-ab88-41d1-a418-e49e1819fdba/installation-3.5.6/lib/slf4j-nop-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
2019-06-27 14:50:17.617+0000 INFO  Initiating metrics...
2019-06-27 14:50:17.640+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@75f65e45' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\anwu\.Neo4jDesktop\neo4jDatabases\database-5bf995b6-ab88-41d1-a418-e49e1819fdba\installation-3.5.6\data\databases\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@75f65e45' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\anwu\.Neo4jDesktop\neo4jDatabases\database-5bf995b6-ab88-41d1-a418-e49e1819fdba\installation-3.5.6\data\databases\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@75f65e45' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\anwu\.Neo4jDesktop\neo4jDatabases\database-5bf995b6-ab88-41d1-a418-e49e1819fdba\installation-3.5.6\data\databases\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@75f65e45' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\anwu\.Neo4jDesktop\neo4jDatabases\database-5bf995b6-ab88-41d1-a418-e49e1819fdba\installation-3.5.6\data\databases\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, C:\Users\anwu\.Neo4jDesktop\neo4jDatabases\database-5bf995b6-ab88-41d1-a418-e49e1819fdba\installation-3.5.6\data\databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@6aecbb8d' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\anwu\.Neo4jDesktop\neo4jDatabases\database-5bf995b6-ab88-41d1-a418-e49e1819fdba\installation-3.5.6\data\databases\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
	... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Store and its lock file has been locked by another process: C:\Users\anwu\.Neo4jDesktop\neo4jDatabases\database-5bf995b6-ab88-41d1-a418-e49e1819fdba\installation-3.5.6\data\databases\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
	at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:116)
	at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:92)
	at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:61)
	at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 11 more
2019-06-27 14:50:17.641+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by Anqi525** [comment]
Solved, thank you Christophe for helping
