### ISSUE TITLE
ERROR The ResourceConfig instance does not contain any root resource classes.

### ISSUE THREAD

**Issue by dinfer** [graphaware/neo4j-nlp#151]
the command:

```
docker run -it --rm -e "NEO4J_AUTH=none" -p 7474:7474 -p 7687:7687 -v `pwd`/neo4j/data:/data -v `pwd`/neo4j/plugins:/plugins -e "NEO4J_dbms_unmanaged__extension__classes=com.graphaware.server=/graphaware" -e "NEO4J_com_graphaware_runtime_enabled=true" -e "NEO4J_com_graphaware_module_NLP_1=com.graphaware.nlp.module.NLPBootstrapper" -e "NEO4J_dbms_security_procedures_whitelist=ga.nlp.*"  neo4j:3.5.4
```

the jar files I downloaded

```
-rwx------ 1 tutu tutu  65940308 8月   2 17:13 graphaware-nlp-3.5.4.53.16.jar*
-rwx------ 1 tutu tutu  13982638 8月   2 17:13 graphaware-server-enterprise-all-3.5.4.53.jar*
-rwx------ 1 tutu tutu  15820620 8月   2 17:13 nlp-stanfordnlp-3.5.4.53.17.jar*
-rwx------ 1 tutu tutu 362565193 8月   2 17:13 stanford-corenlp-3.9.2-models.jar*
```

the error log

```
tutu@dev-server-1:~/km$ docker run -it --rm -e "NEO4J_AUTH=none" -p 7474:7474 -p 7687:7687 -v `pwd`/neo4j/data:/data -v `pwd`/neo4j/plugins:/plugins -e "NEO4J_dbms_unmanaged__extension__classes=com.graphaware.server=/graphaware" -e "NEO4J_com_graphaware_runtime_enabled=true" -e "NEO4J_com_graphaware_module_NLP.1=com.graphaware.nlp.module.NLPBootstrapper" -e "NEO4J_dbms_security_procedures_whitelist=ga.nlp.*"  neo4j:3.5.4
Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2019-08-02 10:43:36.485+0000 WARN  Unknown config option: causal_clustering.discovery_listen_address
2019-08-02 10:43:36.491+0000 WARN  Unknown config option: causal_clustering.raft_advertised_address
2019-08-02 10:43:36.491+0000 WARN  Unknown config option: causal_clustering.raft_listen_address
2019-08-02 10:43:36.492+0000 WARN  Unknown config option: ha.host.coordination
2019-08-02 10:43:36.492+0000 WARN  Unknown config option: causal_clustering.transaction_advertised_address
2019-08-02 10:43:36.493+0000 WARN  Unknown config option: causal_clustering.discovery_advertised_address
2019-08-02 10:43:36.494+0000 WARN  Unknown config option: ha.host.data
2019-08-02 10:43:36.494+0000 WARN  Unknown config option: causal_clustering.transaction_listen_address
2019-08-02 10:43:36.531+0000 INFO  ======== Neo4j 3.5.4 ========
2019-08-02 10:43:36.554+0000 INFO  Starting...
2019-08-02 10:43:41.249+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2019-08-02 10:43:44.371+0000 INFO  Started.
2019-08-02 10:43:44.799+0000 INFO  Mounted unmanaged extension [com.graphaware.server] at [/graphaware]
2019-08-02 10:43:45.634+0000 ERROR The ResourceConfig instance does not contain any root resource classes.
2019-08-02 10:43:45.635+0000 WARN  unavailable The ResourceConfig instance does not contain any root resource classes.
com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
	at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:330)
	at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:160)
	at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:290)
	at org.neo4j.server.AbstractNeoServer.access$900(AbstractNeoServer.java:102)
	at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(AbstractNeoServer.java:543)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:123)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
2019-08-02 10:43:45.705+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474: org.neo4j.server.web.NeoServletContainer-734fbae3@88d2394f==org.neo4j.server.web.NeoServletContainer,jsp=null,order=-1,inst=false
2019-08-02 10:43:45.722+0000 INFO  Stopping...
2019-08-02 10:43:46.046+0000 INFO  Stopped.
2019-08-02 10:43:46.048+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@1fc1c7e' was successfully initialized, but failed to start. Please see the attached cause exception "The ResourceConfig instance does not contain any root resource classes.". Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@1fc1c7e' was successfully initialized, but failed to start. Please see the attached cause exception "The ResourceConfig instance does not contain any root resource classes.".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@1fc1c7e' was successfully initialized, but failed to start. Please see the attached cause exception "The ResourceConfig instance does not contain any root resource classes.".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:123)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@1fc1c7e' was successfully initialized, but failed to start. Please see the attached cause exception "The ResourceConfig instance does not contain any root resource classes.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-734fbae3@88d2394f==org.neo4j.server.web.NeoServletContainer,jsp=null,order=-1,inst=false
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:691)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:330)
	at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:160)
	at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:290)
	at org.neo4j.server.AbstractNeoServer.access$900(AbstractNeoServer.java:102)
	at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(AbstractNeoServer.java:543)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
	at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
	... 27 more
2019-08-02 10:43:46.054+0000 INFO  Neo4j Server shutdown initiated by request

```

**Comment by KimoyoLabs** [comment]
Hi is there any update on this problem?
