### ISSUE TITLE
Unable to deploy plugin on cluster

### ISSUE THREAD

**Issue by NatElkins** [graphaware/neo4j-nlp#154]
Hi,

This morning my coworker and I unsuccessfully tried to deploy this plugin on our production cluster.  We weren't able to get it working, and had some issues where writes were failing to Neo4J.  Only after completely rolling back all changes were we able to get the cluster fully operational again.  Our development environment is a single cluster, and we had no issues installing the plugin there.  Hopefully you can point us in the right direction!

In both dev and prod, we are running Neo4J Enterprise 3.4.7.  Our production cluster has three nodes.

Here's the contents of our plugins that we put into both dev and prod:
```
apoc-3.4.0.2-all.jar
graph-algorithms-algo-3.4.4.0.jar
graphaware-nlp-3.4.7.52.13.jar
graphaware-server-enterprise-all-3.4.7.52.jar
neo4j-graphql-3.4.0.1.jar
nlp-stanfordnlp-3.4.7.52.13.jar
stanford-english-corenlp-2018-10-05-models.jar
```

Here are the configuration changes we made.  As far as we know, we followed the instructions for deployment as expected:
```
  dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
  com.graphaware.runtime.enabled=true
  com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
  dbms.security.procedures.whitelist=ga.nlp.*
```

Our deployment method to our production cluster was to add the jars to the plugin folder, make the configuration changes, and then do rolling restarts of each node.  On restart of our production cluster nodes, we noticed that we got hundreds of log messages similar to the following:

```
2019-11-21 11:15:03.117+0000 WARN [o.n.k.i.p.Procedures] Failed to load `org.apache.xmlbeans.impl.jam.annotation.LineDelimitedTagParser` from plugin jar `/var/lib/neo4j/plugins/graphaware-nlp-3.4.7.52.13.jar`: com/sun/javadoc/Tag
```
They were all warn statements though, so it was unclear whether this was something to worry about.

Whenever we tried to call something from ga.nlp.* though, an exception would be thrown.  Here's our log:
```
2019-11-21 12:02:15.790+0000 WARN [c.g.r.m.BaseTxDrivenModuleManager] Module NLP threw an exception
java.lang.NullPointerException
	at com.graphaware.nlp.module.NLPModule.beforeCommit(NLPModule.java:85)
	at com.graphaware.nlp.module.NLPModule.beforeCommit(NLPModule.java:35)
	at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.beforeCommit(BaseTxDrivenModuleManager.java:204)
	at com.graphaware.runtime.TxDrivenRuntime.beforeCommit(TxDrivenRuntime.java:76)
	at com.graphaware.runtime.TxDrivenRuntime.beforeCommit(TxDrivenRuntime.java:39)
	at org.neo4j.kernel.internal.TransactionEventHandlers.beforeCommit(TransactionEventHandlers.java:124)
	at org.neo4j.kernel.internal.TransactionEventHandlers.beforeCommit(TransactionEventHandlers.java:49)
	at org.neo4j.kernel.impl.api.TransactionHooks.beforeCommit(TransactionHooks.java:60)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:620)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:550)
	at org.neo4j.internal.kernel.api.Transaction.close(Transaction.java:189)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:407)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.run(TransactionStateMachine.java:309)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:81)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:457)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:225)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:69)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:87)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

At this point we really weren't sure what was wrong, and started throwing things at the wall to see what would stick.  We tried things like changing `com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper` to `com.graphaware.module.NLP.2=com.graphaware.nlp.module.NLPBootstrapper`.  At one point we were able to get the leader working, but it wasn't clear why, and when we would bring it down and let another node be elected as leader, we got the same NullPointerException issues.

As we were doing this, we realized that all of our writes were failing with the following error:
```
Neo.ClientError.Transaction.TransactionHookFailed
```

Ultimately we had to revert all config changes and restart to get everything operating again.

Currently we are creating another test cluster to test installation and try to narrow down the problem.  In the meantime, do you have any advice for deploying this plugin in a cluster?

Thanks!

**Comment by NatElkins** [comment]
After testing, it appears to be an issue with leader election.

When the cluster first comes up, we are able to use the plugin on the leader, and writes succeed as normal.

If that leader goes down, a new leader is elected.  On that new leader, not only does the GraphAware plugin fail, but all writes fail as well (TransactionHookFailed).  The cluster enters an unrecoverable state, even if the original node rejoins, and even the original node is elected leader again by restarting the other nodes, the GraphAware plugin does not function and all writes fail.

The only way to "recover" is by shutting down all three nodes and letting the cluster form from scratch again.  We found that no matter which node was elected leader (whether it was the original leader that worked the first time around, or a new leader this time), the GraphAware plugin succeeded and writes succeeded as well.

Please let me know if you require any additional details, or if there's anything we can do to help track down the root cause of this issue.

**Comment by ikwattro** [comment]
Hi @NatElkins 

Indeed, the NLP plugins, and potentially other plugins, do not work on a cluster without a GraphAware Commercial Subscription which would give you access to an updated version of the framework supporting cluster environments.

Feel free to contact info@graphaware.com for a quote.

**Comment by NatElkins** [comment]
@ikwattro Can I suggest putting that in https://github.com/graphaware/neo4j-nlp#feature-matrix ?  As far as I can see, that piece of information does not appear anywhere in this repository.

Also, just out of curiosity, what is the purpose of the 1 vs 2 in `com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper` ?
