### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by good-marketing** [graphaware/neo4j-nlp#28]
Hi,

I try to run the nlp framework on a clean 3.3 edition. 

My plugin dir is

- graphaware-server-community-all-3.3.0.51.jar
- graphaware-nlp-3.3.0.51.1.jar
- nlp-opennlp-3.3.0.51.1.jar
- nlp-stanfordnlp-3.3.0.51.1.jar

I am not sure what I am doing wrong but neo4j will not start, see error below. Thanks for your help.

Bob

======

2017-11-08 21:10:51.647+0000 INFO  ======== Neo4j 3.3.0 ========
2017-11-08 21:10:51.683+0000 INFO  Starting...
2017-11-08 21:11:02.636+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2017-11-08 21:11:08.563+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2017-11-08 21:11:08.581+0000 WARN  Topology change adapter is not available on community edition
2017-11-08 21:11:08.582+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NLP, using com.graphaware.nlp.module.NLPBootstrapper
2017-11-08 21:11:08.640+0000 INFO  Registering module NLP with GraphAware Runtime.
2017-11-08 21:11:08.641+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2017-11-08 21:11:12.630+0000 INFO  Shutting down GraphAware Runtime... 
2017-11-08 21:11:12.632+0000 INFO  Shutting down module NLP
2017-11-08 21:11:12.632+0000 INFO  Terminating task scheduler...
2017-11-08 21:11:12.633+0000 INFO  Task scheduler terminated successfully.
2017-11-08 21:11:12.633+0000 INFO  GraphAware Runtime shut down.
2017-11-08 21:11:12.634+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Could not start GraphAware Runtime because the database didn't get to a usable state within 5 minutes.
2017-11-08 21:11:12.639+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1e86b2d1' was successfully initialized, but failed to start. Please see the attached cause exception **"Cannot inherit from final class".** Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1e86b2d1' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1e86b2d1' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1e86b2d1' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:210)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/Bob/Desktop/neo4j-aws-3.3.0/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@6a1b4854' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:141)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:118)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:82)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:275)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2017-11-08 21:11:12.640+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by good-marketing** [comment]
I think i found the problem. I included apoc-3.3.0.1-all.jar in the plugin folder. If i remove this then neo4j starts fine. If I include it I get the error above. Perhaps a naming conflict ?

**Comment by vince-bickers** [comment]
Please check that you have un-sandboxed the apoc-3.3.0.1-all.jar. Neo4j 3.0 won't start without this in the neo4j.conf:

```dbms.security.procedures.unrestricted=apoc.*```

**Comment by good-marketing** [comment]
Thanks for your comment. 

Here is my conf content, so that may not be the problem...

#********************************************************************
# Apoc
#********************************************************************

dbms.security.procedures.unrestricted=apoc.*
apoc.import.file.enabled=true

#********************************************************************
# Graphaware
#********************************************************************

dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.enabled=true
com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper

**Comment by ikwattro** [comment]
Hi @good-marketing 

Can you please do a `ls -l` on the plugins directory and tell me which user is running the neo4j process, I just test running an instance with APOC and I have no issues : 

```
ikwattro@graphaware-pro ~/d/neo4j-enterprise-3.3.0> ll plugins/
total 882784
-rw-r--r--@ 1 ikwattro  staff   6.9M Nov  9 10:52 apoc-3.3.0.1-all.jar
-rw-r--r--  1 ikwattro  staff   6.4M Nov  8 00:48 graphaware-nlp-3.3.0.51.1.jar
-rw-r--r--@ 1 ikwattro  staff    13M Nov  9 10:55 graphaware-server-enterprise-all-3.3.0.51.jar
-rw-r--r--  1 ikwattro  staff    44M Nov  8 00:56 nlp-opennlp-3.3.0.51.1.jar
-rw-r--r--  1 ikwattro  staff   360M Nov  8 01:02 nlp-stanfordnlp-3.3.0.51.1.jar
```

<img width="1322" alt="screen shot 2017-11-09 at 10 59 39" src="https://user-images.githubusercontent.com/1222009/32599642-6e57ace2-c53d-11e7-9c7b-241791559a24.png">

**Comment by good-marketing** [comment]
Sure, here is my output

total 882704
-rw-r--r--@ 1 Bob  staff    7271085  9 nov 08:26 apoc-3.3.0.1-all.jar
-rw-r--r--@ 1 Bob  staff    6704427  8 nov 21:13 graphaware-nlp-3.3.0.51.1.jar
-rw-r--r--@ 1 Bob  staff   13666555  8 nov 21:05 graphaware-server-community-all-3.3.0.51.jar
-rw-r--r--@ 1 Bob  staff   46370876  8 nov 21:27 nlp-opennlp-3.3.0.51.1.jar
-rw-r--r--@ 1 Bob  staff  377919096  8 nov 21:31 nlp-stanfordnlp-3.3.0.51.1.jar

**Comment by ikwattro** [comment]
How is Neo4j running? With desktop, dmg installer, tarball ?

**Comment by good-marketing** [comment]
Tarball on a MacOs
I also tried to run with enterprise framework however it has the same error message...

**Comment by good-marketing** [comment]
I tried the same set up on a different machine, and got the same error. 

I can run Apoc and NLP framework fine independently. If I try to use them together however get the error stated above. I'd like to use the apoc.iterate and nest within this call, ga.nlp. annotate etc. 

I am running community Neo4j 3.3.0 on Mac 10.11.6 , with the plugins states above. 

@jexp do you have an idea of what could be the problem? Thanks!

**Comment by ikwattro** [comment]
We are running the exact same setup for a current customer, without any issues.

![screen shot 2017-11-11 at 16 53 03](https://user-images.githubusercontent.com/1222009/32690993-e5e8413a-c700-11e7-86ea-b9badc395f67.png)

![screen shot 2017-11-11 at 16 52 45](https://user-images.githubusercontent.com/1222009/32690995-ebb7f006-c700-11e7-8ec5-cf0fac7d3ced.png)

**Comment by ikwattro** [comment]
Allright, with Community it fails. sorry about that.

```
2017-11-11 16:03:28.449+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3df7e309' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3df7e309' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3df7e309' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3df7e309' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:210)
	... 3 more
```

**Comment by ikwattro** [comment]
It seems that it is coming from apoc, I have the same issue on 3.3.0 community and apoc alone

**Comment by pgbda-grp3** [comment]
Hi 
Followed the steps mentioned here https://github.com/graphaware/ 
Have Neo4jCE installed on windows with 8gb RAM .After the plugins are placed and the configuration changed getting an out of memory error 

Have posted the same issue on stackoverflow .https://stackoverflow.com/questions/47646866/neo4j-3-3-0-community-edition-open-nlp

Any suggestions to resolve this ?

thanks
Sunil Vikram

**Comment by ikwattro** [comment]
Closing this issue as it is related to the neo4j framework and not the nlp plugin.
