### ISSUE TITLE
ERROR Unsupported language : n/a -- Java 1.8.0_161

### ISSUE THREAD

**Issue by fotisz** [graphaware/neo4j-nlp#61]
2018-03-07 20:47:09.391+0000 ERROR Unsupported language : n/a
java.lang.RuntimeException: Unsupported language : n/a
	at com.graphaware.nlp.NLPManager.checkTextLanguage(NLPManager.java:253)
	at com.graphaware.nlp.NLPManager.annotateTextAndPersist(NLPManager.java:135)
	at com.graphaware.nlp.NLPManager.annotateTextAndPersist(NLPManager.java:130)
	at com.graphaware.nlp.dsl.procedure.AnnotateProcedure.annotate(AnnotateProcedure.java:39)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:598)
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.callProcedure(ProcedureRegistry.java:201)
	at org.neo4j.kernel.impl.proc.Procedures.callProcedure(Procedures.java:256)
	at org.neo4j.kernel.impl.api.OperationsFacade.callProcedure(OperationsFacade.java:1440)
	at org.neo4j.kernel.impl.api.OperationsFacade.procedureCallWrite(OperationsFacade.java:1394)
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext$$anonfun$20.apply(TransactionBoundQueryContext.scala:706)
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext$$anonfun$20.apply(TransactionBoundQueryContext.scala:706)
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext.callProcedure(TransactionBoundQueryContext.scala:726)
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext.callReadWriteProcedure(TransactionBoundQueryContext.scala:707)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:153)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:153)
	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:39)
	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateIterator(ExceptionTranslationSupport.scala:45)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateIterator(ExceptionTranslatingQueryContext.scala:39)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.callReadWriteProcedure(ExceptionTranslatingQueryContext.scala:153)
	at org.neo4j.cypher.internal.spi.v3_3.DelegatingQueryContext.callReadWriteProcedure(DelegatingQueryContext.scala:217)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.EagerReadWriteCallMode.callProcedure(ProcedureCallMode.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ProcedureCallPipe$$anon$$$$ad93371f26992c1f243949f3f9c28e5$$$$ateResultsByAppending$1.apply(ProcedureCallPipe.scala:68)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ProcedureCallPipe$$anon$$$$ad93371f26992c1f243949f3f9c28e5$$$$ateResultsByAppending$1.apply(ProcedureCallPipe.scala:66)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator$$anonfun$hasNext$1.apply$mcZ$sp(ResultIterator.scala:59)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator$$anonfun$hasNext$1.apply(ResultIterator.scala:57)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator$$anonfun$hasNext$1.apply(ResultIterator.scala:57)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator$$anonfun$failIfThrows$1.apply(ResultIterator.scala:84)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator.decoratedCypherException(ResultIterator.scala:93)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator.failIfThrows(ResultIterator.scala:82)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator.hasNext(ResultIterator.scala:56)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator.foreach(ResultIterator.scala:48)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator.to(ResultIterator.scala:48)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:294)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator.toList(ResultIterator.scala:48)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.EagerResultIterator.<init>(ResultIterator.scala:34)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.ClosingIterator.toEager(ResultIterator.scala:52)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.buildResultIterator(DefaultExecutionResultBuilderFactory.scala:120)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:103)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:74)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:100)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:83)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$InterpretedExecutionPlan.run(BuildInterpretedExecutionPlan.scala:116)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:183)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:179)
	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper.run(Compatibility.scala:179)
	at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:120)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:62)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI$1.start(TransactionStateMachineSPI.java:146)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:247)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:82)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:408)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:200)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:152)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)

**Comment by ikwattro** [comment]
When opening an issue, please at least provide some context, such as 

1. Neo4j version used and the version of the plugins
2. The query you used
3. The text you are trying to process.

Please re-open and provide those informations.
