### ISSUE TITLE
Exception in thread "GraphAware Starter" java.lang.NoSuchFieldError: pipelineInfos

### ISSUE THREAD

**Issue by glaulom** [graphaware/neo4j-nlp#79]
When trying to use GraphAware Natural Language Processing with the following **environment** : 
**OS  :** Windows 10 Family 64bits
**Neo4J :** neo4j-community-3.3.5

 **And the plugins :** 
- nlp-opennlp-3.3.2.52.6.jar
- graphaware-nlp-3.3.3.52.7.jar
- graphaware-server-community-all-3.3.3.52.jar

I'm getting this error after runing **bin\neo4j console** :
> C:\Program Files\neo4j-community-3.3.5>bin\neo4j console
2018-05-18 13:18:34.316+0000 INFO  ======== Neo4j 3.3.5 ========
2018-05-18 13:18:34.476+0000 INFO  Starting...
2018-05-18 13:18:40.353+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-05-18 13:18:46.218+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-05-18 13:18:46.349+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NLP, using com.graphaware.nlp.module.NLPBootstrapper2018-05-18 13:18:46.706+0000 INFO  Registering module NLP with GraphAware Runtime.
2018-05-18 13:18:46.715+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2018-05-18 13:20:21.594+0000 INFO  Starting GraphAware...
2018-05-18 13:20:21.602+0000 INFO  Loading module metadata...
2018-05-18 13:20:21.607+0000 INFO  Loading metadata for module NLP
2018-05-18 13:20:21.860+0000 INFO  Module NLP seems to have been registered for the first time.
2018-05-18 13:20:21.863+0000 INFO  Module NLP seems to have been registered for the first time, will try to initialize...
2018-05-18 13:20:21.866+0000 INFO  InitializeUntil set to 9223372036854775807 and it is 1526649621866. Will initialize.
2018-05-18 13:20:21.869+0000 INFO  Initializing Community NLP Module
[GraphAware Starter] INFO org.reflections.Reflections - Reflections took 1271 ms to scan 3 urls, producing 238 keys and 519 values
2018-05-18 13:20:23.222+0000 INFO  Loading text processor: com.graphaware.nlp.processor.opennlp.OpenNLPTextProcessor with class: com.graphaware.nlp.processor.opennlp.OpenNLPTextProcessor
2018-05-18 13:20:43.329+0000 INFO  Started.
2018-05-18 13:20:44.087+0000 INFO [c.g.s.f.b.GraphAwareServerBootstrapper] started
2018-05-18 13:20:44.090+0000 INFO  Mounted unmanaged extension [com.graphaware.server] at [/graphaware]
2018-05-18 13:20:45.167+0000 INFO  Google Analytics enabled
Exception in thread "GraphAware Starter" java.lang.NoSuchFieldError: pipelineInfos
        at com.graphaware.nlp.processor.opennlp.OpenNLPTextProcessor.createFullPipeline(OpenNLPTextProcessor.java:80)
        at com.graphaware.nlp.processor.opennlp.OpenNLPTextProcessor.init(OpenNLPTextProcessor.java:51)
        at com.graphaware.nlp.processor.TextProcessorsManager.lambda$initiateTextProcessors$1(TextProcessorsManager.java:61)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.graphaware.nlp.processor.TextProcessorsManager.initiateTextProcessors(TextProcessorsManager.java:60)
        at com.graphaware.nlp.processor.TextProcessorsManager.<init>(TextProcessorsManager.java:37)
        at com.graphaware.nlp.NLPManager.init(NLPManager.java:105)
        at com.graphaware.nlp.module.NLPModule.initialize(NLPModule.java:62)
        at com.graphaware.runtime.manager.ProductionTxDrivenModuleManager.initialize(ProductionTxDrivenModuleManager.java:57)
        at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.initializeIfAllowed(BaseTxDrivenModuleManager.java:128)
        at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.handleNoMetadata(BaseTxDrivenModuleManager.java:72)
        at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.handleNoMetadata(BaseTxDrivenModuleManager.java:39)
        at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:143)
        at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:125)
        at com.graphaware.runtime.TxDrivenRuntime.loadMetadata(TxDrivenRuntime.java:130)
        at com.graphaware.runtime.ProductionRuntime.loadMetadata(ProductionRuntime.java:80)
        at com.graphaware.runtime.BaseGraphAwareRuntime.startModules(BaseGraphAwareRuntime.java:154)
        at com.graphaware.runtime.TxDrivenRuntime.startModules(TxDrivenRuntime.java:146)
        at com.graphaware.runtime.ProductionRuntime.startModules(ProductionRuntime.java:70)
        at com.graphaware.runtime.BaseGraphAwareRuntime.start(BaseGraphAwareRuntime.java:134)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.lambda$start$9(RuntimeKernelExtension.java:117)
        at java.lang.Thread.run(Unknown Source)

I've tried with another version of nlo-opennlp but still getting the exact same error.

**Comment by ikwattro** [comment]
Hi, yes opennlp is one version behind, you can try with stanford the time we upgrade it.

**Comment by ikwattro** [comment]
Opened this one for tracking. https://github.com/graphaware/neo4j-nlp-opennlp/issues/6
