### ISSUE TITLE
Index out of bounds exception during annotation leading to failed commits

### ISSUE THREAD

**Issue by fotisz** [graphaware/neo4j-nlp#80]
**Config:** 
Neo4J Desktop 1.1.1
Neo4J 3.3.5 Enterprise 
_plugins:_ 
apoc-3.3.0.3
graphaware-nlp-3.3.3.52.7
graphaware-server-enterprise-all-3.3.3.52
nlp-stanfordnlp-3.3.3.52.7

I am running an annotation using Stanford CoreNLP (w. true:ner, sentiment, relations, dependency) and I seem to be getting a lot of errors, notably (see also logs below):

 - java.lang.IllegalArgumentException: Got a close tag p which does not match any open tag
 - java.lang.IndexOutOfBoundsException

Any suggestions? 

**From the logs:** 
```
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] Error during iterate.commit:
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 1396 times: org.neo4j.graphdb.TransactionFailureException: Transaction was marked as successful, but unable to commit transaction so rolled back.
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] Error during iterate.execute:
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 12 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IllegalArgumentException: Got a close tag p which does not match any open tag
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 206 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 2 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.NullPointerException
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 4 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 8, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 1 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 10, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 2 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 7, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 11 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 4, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 1032 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 23 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 4 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 2 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 12, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 86 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
2018-05-19 16:22:17.721+0000 WARN [o.n.k.i.p.Procedures] 11 times: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
2018-05-19 16:26:39.826+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [5098]:  Starting check pointing...
2018-05-19 16:26:39.826+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [5098]:  Starting store flush...
2018-05-19 16:26:40.061+0000 INFO [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 5098 to [C:\Users\Fotis.Zapantis\.Neo4jDesktop\neo4jDatabases\database-80a77733-2c74-4a9b-9a81-697a3d63f8ca\installation-3.3.5\data\databases\graph.db\neostore.counts.db.b], from [C:\Users\Fotis.Zapantis\.Neo4jDesktop\neo4jDatabases\database-80a77733-2c74-4a9b-9a81-697a3d63f8ca\installation-3.3.5\data\databases\graph.db\neostore.counts.db.a].
2018-05-19 16:26:40.092+0000 INFO [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 5098 to [C:\Users\Fotis.Zapantis\.Neo4jDesktop\neo4jDatabases\database-80a77733-2c74-4a9b-9a81-697a3d63f8ca\installation-3.3.5\data\databases\graph.db\neostore.counts.db.b], from [C:\Users\Fotis.Zapantis\.Neo4jDesktop\neo4jDatabases\database-80a77733-2c74-4a9b-9a81-697a3d63f8ca\installation-3.3.5\data\databases\graph.db\neostore.counts.db.a].
2018-05-19 16:26:45.266+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [5098]:  Store flush completed
2018-05-19 16:26:45.266+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [5098]:  Starting appending check point entry into the tx log...
2018-05-19 16:26:45.266+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [5098]:  Appending check point entry into the tx log completed
2018-05-19 16:26:45.266+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [5098]:  Check pointing completed
2018-05-19 16:26:45.266+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [0]:  Starting log pruning.
2018-05-19 16:26:45.266+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [0]:  Log pruning complete.
2018-05-19 17:45:39.866+0000 INFO [o.n.c.i.ExecutionEngine] Discarded stale query from the query cache after 17599 seconds: MATCH (a)-[r]->(b) WHERE id(a) IN $existingNodeIds AND id(b) IN $newNodeIds RETURN r;
2018-05-19 17:45:39.881+0000 INFO [o.n.c.i.EnterpriseCompatibilityFactory] Discarded stale query from the query cache after 17599 seconds: MATCH (a)-[r]->(b) WHERE id(a) IN $existingNodeIds AND id(b) IN $newNodeIds RETURN r;
2018-05-19 17:46:41.965+0000 INFO [o.n.k.i.p.Procedures] starting batching from `MATCH (n:Record) WHERE NOT (n)-[:HAS_ANNOTATED_TEXT]->() AND EXISTS (n.Text) AND length(n.Text) > 30 AND length(n.Text) < 2000 RETURN n` operation using iteration `CALL ga.nlp.annotate({text:n.Text, id:id(n), checkLanguage: false}) YIELD result MERGE(n)-[:HAS_ANNOTATED_TEXT]->(result)` in separate thread
2018-05-19 17:46:41.968+0000 INFO [c.g.n.u.ProcessorUtils] Taking default pipeline from configuration : customStopWords2
```

**AND**

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.graphaware.nlp.processor.stanford.StanfordTextProcessor.extractRelationship(StanfordTextProcessor.java:319)
	at com.graphaware.nlp.processor.stanford.StanfordTextProcessor.lambda$annotateText$0(StanfordTextProcessor.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.graphaware.nlp.processor.stanford.StanfordTextProcessor.annotateText(StanfordTextProcessor.java:107)
	at com.graphaware.nlp.NLPManager.annotateTextAndPersist(NLPManager.java:143)
	at com.graphaware.nlp.NLPManager.annotateTextAndPersist(NLPManager.java:131)
	at com.graphaware.nlp.dsl.procedure.AnnotateProcedure.annotate(AnnotateProcedure.java:39)
	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:596)
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.callProcedure(ProcedureRegistry.java:202)
	at org.neo4j.kernel.impl.proc.Procedures.callProcedure(Procedures.java:257)
	at org.neo4j.kernel.impl.api.OperationsFacade.callProcedure(OperationsFacade.java:1440)
	at org.neo4j.kernel.impl.api.OperationsFacade.procedureCallWrite(OperationsFacade.java:1394)
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext$$anonfun$20.apply(TransactionBoundQueryContext.scala:706)
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext$$anonfun$20.apply(TransactionBoundQueryContext.scala:706)
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext.callProcedure(TransactionBoundQueryContext.scala:729)
	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext.callReadWriteProcedure(TransactionBoundQueryContext.scala:707)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:153)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:153)
	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:39)
	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateIterator(ExceptionTranslationSupport.scala:46)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateIterator(ExceptionTranslatingQueryContext.scala:39)
	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.callReadWriteProcedure(ExceptionTranslatingQueryContext.scala:153)
	at org.neo4j.cypher.internal.spi.v3_3.DelegatingQueryContext.callReadWriteProcedure(DelegatingQueryContext.scala:217)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.EagerReadWriteCallMode.callProcedure(ProcedureCallMode.scala:55)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ProcedureCallPipe$$anon$$$$ad93371f26992c1f243949f3f9c28e5$$$$ateResultsByAppending$1.apply(ProcedureCallPipe.scala:68)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.ProcedureCallPipe$$anon$$$$ad93371f26992c1f243949f3f9c28e5$$$$ateResultsByAppending$1.apply(ProcedureCallPipe.scala:66)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:28)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:62)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.pipes.PipeWithSource.createResults(Pipe.scala:59)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:102)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:74)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:100)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:83)
	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.BuildInterpretedExecutionPlan$InterpretedExecutionPlan.run(BuildInterpretedExecutionPlan.scala:116)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:183)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:179)
	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper.run(Compatibility.scala:179)
	at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:120)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:62)
	at org.neo4j.kernel.impl.proc.ProcedureGDBFacadeSPI.executeQuery(ProcedureGDBFacadeSPI.java:143)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:451)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:434)
	at apoc.periodic.Periodic.lambda$iterate$8(Periodic.java:266)
	at apoc.periodic.Periodic.retry(Periodic.java:272)
	at apoc.periodic.Periodic.lambda$iterateAndExecuteBatchedInSeparateThread$12(Periodic.java:339)
	at apoc.util.Util.lambda$inTxFuture$4(Util.java:172)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ikwattro** [comment]
Confirmed issue in our stanford-nlp code, will fix

**Comment by fotisz** [comment]
Would that be the snapshot:
https://www.dropbox.com/s/n6q5ctb7ca2hrms/nlp-stanfordnlp-3.4.0.52.9-SNAPSHOT.jar?dl=0

mentioned in #86?

**Comment by ikwattro** [comment]
No it is not solved yet, will be this week.

**Comment by ikwattro** [comment]
@fotisz 3.4.0.52.11 contains the fix https://products.graphaware.com/download/nlp-stanford-nlp/nlp-stanfordnlp-3.4.0.52.11.jar

**Comment by fotisz** [comment]
many thanks!
