### ISSUE TITLE
Unable to start neo4j server. Getting the following error. Kindly help me resolve this.

### ISSUE THREAD

**Issue by astrude** [graphaware/neo4j-nlp#81]
2018-05-21 16:14:13.467+0000 INFO  Starting...
2018-05-21 16:14:19.615+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-05-21 16:14:25.887+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-05-21 16:14:25.915+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NLP, using com.graphaware.nlp.module.NLPBootstrapper
2018-05-21 16:14:26.003+0000 INFO  Registering module NLP with GraphAware Runtime.
2018-05-21 16:14:26.005+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2018-05-21 16:14:49.456+0000 INFO  Shutting down GraphAware Runtime... 
2018-05-21 16:14:49.456+0000 INFO  Shutting down module NLP
2018-05-21 16:14:49.456+0000 INFO  Terminating task scheduler...
2018-05-21 16:14:49.457+0000 INFO  Task scheduler terminated successfully.
2018-05-21 16:14:49.457+0000 INFO  GraphAware Runtime shut down.
2018-05-21 16:14:49.462+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Could not start GraphAware Runtime because the database didn't get to a usable state within 5 minutes.
2018-05-21 16:14:49.464+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@59d31e9e' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@59d31e9e' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@59d31e9e' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@59d31e9e' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /usr/local/Cellar/neo4j/3.3.4/libexec/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@6b0e2e81' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:141)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:118)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:82)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:276)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2018-05-21 16:14:49.465+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by ikwattro** [comment]
Please provide your neo4j version and the versions of all the plugins used.

**Comment by astrude** [comment]
neo4j version - 3.3.4

<img width="639" alt="screen shot 2018-05-21 at 11 15 33 pm" src="https://user-images.githubusercontent.com/5844703/40321501-ec7d2f1e-5d4c-11e8-9d4e-dc09909102a4.png">

**Comment by ikwattro** [comment]
Can you try by removing opennlp from the plugins

**Comment by astrude** [comment]
same issue after trying the suggestion.

**Comment by astrude** [comment]
this issue is not resolved yet? Could you please suggest ways to resolve it, unable to use graph ware plugin at all, didn't even get a chance to test.

**Comment by ikwattro** [comment]
@astrude Read the comments of the issue you linked ;-)

**Comment by ikwattro** [comment]
Closing for inactivity, please re-open if needed.

**Comment by swraza** [comment]
Hello can anyone help me get out of this error.

Persistence Service could not be started: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory,

using neo4 version 3.2.14 with glassfish 5.0

**Comment by ikwattro** [comment]
We don't have compatible versions for 3.2.x , upgrade to a recent version of Neo4j.

If you cannot, we can provide specific builds of older versions through a commercial agreement.
