### ISSUE TITLE
Cannot inherit from final class

### ISSUE THREAD

**Issue by glaulom** [graphaware/neo4j-nlp#84]
After this issue #79 
I get another error trying to use GraphAware Natural Language Processing with the following environment :
**OS :** Windows 10 Family 64bits
**Neo4J :** neo4j-community-3.3.5

**And the only plugins installed are:**
nlp-stanford-nlp-3.3.2.52.7.jar
graphaware-nlp-3.3.3.52.7.jar
graphaware-server-community-all-3.3.3.52.jar

I'm getting this error after runing bin\neo4j console :

> C:\Program Files\neo4j-community-3.3.5>bin\neo4j console
2018-05-28 12:38:46.981+0000 INFO  ======== Neo4j 3.3.5 ========
2018-05-28 12:38:47.144+0000 INFO  Starting...
2018-05-28 12:38:51.561+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-05-28 12:38:56.313+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-05-28 12:38:56.433+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID NLP, using com.graphaware.nlp.module.NLPBootstrapper
2018-05-28 12:38:56.780+0000 INFO  Registering module NLP with GraphAware Runtime.
2018-05-28 12:38:56.792+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2018-05-28 12:40:24.445+0000 INFO  Shutting down GraphAware Runtime...
2018-05-28 12:40:24.449+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Could not start GraphAware Runtime because the database didn't get to a usable state within 5 minutes.
2018-05-28 12:40:24.449+0000 INFO  Shutting down module NLP
2018-05-28 12:40:24.456+0000 INFO  Terminating task scheduler...
2018-05-28 12:40:24.463+0000 INFO  Task scheduler terminated successfully.
2018-05-28 12:40:24.469+0000 INFO  GraphAware Runtime shut down.
2018-05-28 12:40:24.496+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3123fb56' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3123fb56' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3123fb56' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3123fb56' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Program Files\neo4j-community-3.3.5\data\databases\graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@2175efe4' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
        ... 9 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:141)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:118)
        at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
        at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:82)
        at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:276)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 11 more
2018-05-28 12:40:24.516+0000 INFO  Neo4j Server shutdown initiated by request

I do not get this error with open-nlp (but getting #79 ).

**Comment by ikwattro** [comment]
Please use the framework in 3.3.5 version, I ran 3 days training on windows with neo4j 3.3.5 without issue.
